# Permalinks
permalink:           pretty 

# Setup
title:               Laura Cabello
tagline:             Notebook where I get my work squared away
paginate:            1
baseurl:             "/blog/about/"

# Markdown
markdown: kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Laura Cabello Piqueras
  url:               https://www.linkedin.com/in/laura-cabello-piqueras-167352104

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# This is the list of pages to include in the header of the website.
pages_list:
  About: "/blog/about/"
  Resume: "/blog/resume/"
  Publications: "/blog/publications/"
  Archive: "/blog/archive/"

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
